---

- name: Add PHP5 packages
  yum: name={{ item }} state=latest enablerepo=remi
  with_items:
    - php56
    - php56-php-fpm
    - php56-php-mcrypt
    - php56-php-pgsql
    - php56-php-gd
    - php56-php-mbstring
  tags:
    - php

- name: Remove www pool
  file: path=/opt/remi/php56/root/etc/php-fpm.d/www.conf state=absent
  tags:
    - php

- name: Copy PHP-FPM config file
  template: src=php-fpm.conf.j2 dest=/opt/remi/php56/root/etc/php-fpm.conf owner=root group=root mode=0644
  tags:
    - php

- name: Copy PHP-FPM default pool
  template: src=default.conf.j2 dest=/opt/remi/php56/root/etc/php-fpm.d/default.conf owner=root group=root mode=0644
  tags:
    - php

- name: Restart php-fpm service
  service: name=php56-php-fpm state=started enabled=yes
  tags:
    - php