---

public_keys:
  - username: ravage
    keys:
      - "{{ lookup('file', 'ssh/ravage.pub') }}"
  - username: deployer
    keys:
      - "{{ lookup('file', 'ssh/deployer.pub') }}"

users:
  ravage:
    password: "{{ lookup('password', '../../../credentials/ravage.pwd encrypt=sha512_crypt') }}"
    shell: '/bin/bash'
  deployer:
    password: "{{ lookup('password', '../../../credentials/deployer.pwd encrypt=sha512_crypt') }}"
    shell: '/bin/bash'

ssh:
  port: 22

sudo:
  group: wheel
  users:
    - ravage

ruby:
  version: "2.2.0"
  folder: "2.2"

swap:
  size: 2G
  path: /fs-swap

cache_time: 3600