---

- name: Add NGiNX repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  tags:
    - nginx
    - web

- name: Install NGiNX
  yum: name=nginx state=latest
  tags:
    - nginx
    - web

- name: Copy /etc/nginx/nginx.conf
  template: src=nginx/nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644
  tags:
    - nginx
    - web

- name: Copy NGiNX conf.d support configuration
  copy: src=nginx/{{ item }}
        dest=/etc/nginx/conf.d/{{ item }}
        owner=root group=root
        mode=6440
  with_items:
    - cache
    - drop
    - images
    - mappings
    - php
    - cloudflare.conf
  tags:
    - nginx
    - web

- name: Create sites(enabled/available) directories
  file: path=/etc/nginx/{{ item }} owner=root mode=755 state=directory
  with_items:
    - sites-available
    - sites-enabled
  tags:
    - nginx
    - web

- name: Change permission for cache directory
  file: path=/var/cache/nginx state=directory owner={{ nginx.group }} group={{ nginx.group }}
  tags:
    - nginx
    - web

- name: Create /srv/sites directory
  file: path=/srv/sites owner=root mode=755 state=directory
  notify: restart nginx
  tags:
    - nginx
    - web

- name: Ensure NGiNX is enabled
  service: name=nginx state=started enabled=yes
  tags:
    - nginx
    - web