---

- name: Install Ruby build dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
  tags:
    - ruby-mri

- name: Check if Ruby was previously built by Ansible
  stat: path=/root/.ansible-ruby-{{ ruby.version }}
  register: p
  tags:
    - ruby-mri

- name: Copy build script
  template: src=build.sh.j2 dest=/tmp/build.sh mode=700
  when: not p.stat.exists
  tags:
    - ruby-mri

- name: Run build.sh script
  shell: /tmp/build.sh creates=/root/.ansible-ruby-{{ ruby.version }}
  register: result
  tags:
    - ruby-mri

- name: Create build control file
  file: path=/root/.ansible-ruby-{{ ruby.version }} state=touch
  when: result|success
  tags:
    - ruby-mri

- name: Cleanup Ruby build
  file: path=/tmp/build.sh state=absent
  when: not p.stat.exists
  tags:
    - ruby-mri

- name: Do not build documentation for gems
  lineinfile: "dest=/etc/gemrc create=yes line='gem: --no-ri --no-rdoc --user-install'"
  tags:
    - ruby-mri