---

- name: Add PHP5 packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-fpm
    - php5-mcrypt
    - php5-pgsql
  tags:
    - php

- name: Remove www pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  tags:
    - php

- name: Copy PHP-FPM config file
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/php-fpm.conf owner=root group=root mode=0644
  tags:
    - php

- name: Copy PHP-FPM default pool
  template: src=default.conf.j2 dest=/etc/php5/fpm/pool.d/default.conf owner=root group=root mode=0644
  tags:
    - php

- name: Restart php-fpm service
  service: name=php5-fpm state=restarted enabled=yes
  tags:
    - php