---

- name: Install build-essentials
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
  tags:
    - scripts

- name: Install chruby
  script: install-chruby.sh
  tags:
    - scripts

- name: Install ruby-install
  script: install-ruby-install.sh
  tags:
    - scripts

- name: Setup chruby environment
  copy: src=profile.sh dest=/etc/profile.d/chruby.sh owner=root mode=0755
  tags:
    - scripts
