---

- name: Add RethinkDB APT key
  apt_key: url=http://download.rethinkdb.com/apt/pubkey.gpg
  tags:
    - database
    - rethinkdb

- name: Add RethinkDB repository
  apt_repository: repo="deb http://download.rethinkdb.com/apt {{ ansible_lsb.codename }} main"
  tags:
    - database
    - rethinkdb

- name: Install RethinkDB packages
  apt: name=rethinkdb state=latest update_cache=yes
  tags:
    - database
    - rethinkdb

- name: Copy RethinkDB configuration
  template: src=default.conf.j2
            dest="/etc/rethinkdb/instances.d/{{ ansible_hostname }}.conf"
  tags:
    - database
    - rethinkdb

- name: Create RethinkDB log file
  file: path=/var/log/rethinkdb
        state=touch
        owner=rethinkdb
        group=rethinkdb mode=660
  tags:
    - database
    - rethinkdb

- name: Restart RethinkDB service
  service: name=rethinkdb state=restarted
  tags:
    - database
    - rethinkdb

- name: Ensure RethinkDB service is enabled
  service: name=rethinkdb state=started enabled=yes
  tags:
    - database
    - rethinkdb