---

- name: Install epel-release repository
  yum: name=epel-release state=latest
  tags:
    - nodejs

- name: Install NodeJS packages
  yum: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm
  tags:
    - nodejs