---

public_keys:
  - {
      username: 'ravage',
      key: "{{ lookup('file', 'ssh/ravage.pub') }}"
    }

users:
  - {
      username: 'ravage',
      password: "{{ lookup('password', 'credentials/ravage.pwd encrypt=sha512_crypt') }}"
    }

ssh:
  port: 22

sudo:
  group: wheel
  users: [ ravage ]