---

- name: Install PostgreSQL and development dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags:
    - postgresql
    - db
